name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"  # 监听所有标签推送

permissions:
  contents: write  # 允许写入内容，用于创建发布版本

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 创建发布版本
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css lunar.js
